M48
; DRILL file {KiCad 7.0.2-0} date 2023 October 31, Tuesday 17:00:11
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-31T17:00:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.3512Y-5.4589
X5.4012Y-3.5589
X7.4012Y-4.1589
X7.4012Y-5.2589
T0
M30
