M48
; DRILL file {KiCad 7.0.2-0} date 2024 January 05, Friday 15:54:09
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-05T15:54:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.3512Y-5.4589
X5.4012Y-3.5589
X7.4012Y-4.1589
X7.4012Y-5.2589
T0
M30
